name: Getting Weekly Update

on:
  schedule:
    # Runs at 00:00 UTC on Sunday
    - cron: '0 0 * * 0'
  # manual trigger for testing
  workflow_dispatch:
    
jobs:
  get_release_info:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
    permissions:
      issues: write
    
    steps:
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Execute the script
        run: |
          python weekly_update.py ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }}
